### PR TITLE
Add issue-message to greetings.yml

### PR DESCRIPTION
**Pull request by JesterOrNot**

### CODE REVIEW

**Comment by Kreyren** [comment]
Thanks for contrib appreciated!

This repository is currently in what I call init phase so all the commits with be remade once I decide on quality assurance, documentation method and automation. 

So I'm going to keep this on hold for now and merge it once the repository is able to accept merge requests.

**Comment by JesterOrNot** [comment]
Alright just wanted to say this project seems pretty cool!

**Comment by Kreyren** [comment]
Notice; Still keeping this on hold, but changed the repository structure (github closed this automatically)

**Comment by Kreyren** [comment]
@JesterOrNot If you want you can commit in `init` branch now, but note that all commits from `init` branch will be squashed in `master` as `Initial commit`.

This way i should be able to handle current contribs so any relevant help is welcomed (resolving FIXMEs for example) ^^

**Pull request closed without merging**
